### ISSUE TITLE
I try to use confd in docker, but it says: ERROR 501: All the given peers are not reachable

### ISSUE THREAD

**Issue by HD-DBC** [kelseyhightower/confd#251] opened 2015-04-05 15:27 UTC
I try to use confd in docker, but it says: ERROR 501: All the given peers are not reachable

the related environment:
docker: server version 1.5
confd: version 0.8.0, container's address 172.17.0.3
etcd: version 2.0.5, container's address 172.17.0.1

run command in 172.17.0.3:
                      curl http://172.17.0.1:2379/version
returns:
                      {"releaseVersion":"2.0.5","internalVersion":"2"}

**Comment by bacongobbler** [comment] 2015-04-05 17:59
Confd is incompatible with etcd 2.0 at this time. Closing as a dupe of #195, which is being tracked in #250. Thanks!

**Closed by bacongobbler** 2015-04-05 17:59 UTC

**Comment by mingfang** [comment] 2015-04-21 01:08
This is still a problem with the latest version.

```
etcdctl --version
etcdctl version 2.0.9
```
```
confd --version
confd 0.9.0
```

I started etcd like this
```
etcd -addr=$IP:4001 -bind-addr=0.0.0.0:4001

2015-04-21_00:52:02.09525 2015/04/21 00:52:02 etcd: no data-dir provided, using default data-dir ./default.etcd
2015-04-21_00:52:02.09527 2015/04/21 00:52:02 etcd: listening for peers on http://localhost:2380
2015-04-21_00:52:02.09527 2015/04/21 00:52:02 etcd: listening for peers on http://localhost:7001
2015-04-21_00:52:02.09528 2015/04/21 00:52:02 etcd: listening for client requests on http://0.0.0.0:4001
2015-04-21_00:52:02.09528 2015/04/21 00:52:02 etcdserver: datadir is valid for the 2.0.1 format
2015-04-21_00:52:02.09529 2015/04/21 00:52:02 etcdserver: name = default
2015-04-21_00:52:02.09529 2015/04/21 00:52:02 etcdserver: data dir = default.etcd
2015-04-21_00:52:02.09530 2015/04/21 00:52:02 etcdserver: member dir = default.etcd/member
2015-04-21_00:52:02.09530 2015/04/21 00:52:02 etcdserver: heartbeat = 100ms
2015-04-21_00:52:02.09531 2015/04/21 00:52:02 etcdserver: election = 1000ms
2015-04-21_00:52:02.09531 2015/04/21 00:52:02 etcdserver: snapshot count = 100002015-04-21_00:52:02.09532 2015/04/21 00:52:02 etcdserver: advertise client URLs = http://172.17.0.169:4001
2015-04-21_00:52:02.09532 2015/04/21 00:52:02 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
```

I started confd like this

```
confd -watch=true -interval 30 -backend=etcd -node "http://$ETCD_HOST:4001" -log-level="debug"

2015-04-21_00:52:02.48287 2015-04-20T19:52:02-05:00 boot2docker confd[24]: INFO Backend set to etcd
2015-04-21_00:52:02.48288 2015-04-20T19:52:02-05:00 boot2docker confd[24]: INFO Starting confd
2015-04-21_00:52:02.48288 2015-04-20T19:52:02-05:00 boot2docker confd[24]: INFO Backend nodes set to http://localhost:4001
2015-04-21_00:52:02.48289 2015-04-20T19:52:02-05:00 boot2docker confd[24]: DEBUG Loading template resources from confdir /etc/confd
2015-04-21_00:52:02.48291 2015-04-20T19:52:02-05:00 boot2docker confd[24]: DEBUG Loading template resource from /etc/confd/conf.d/kubernetes.toml
 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
2015-04-21_00:52:04.48578 2015-04-20T19:52:04-05:00 boot2docker confd[24]: ERROR 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

This happens only when etcd and confd are started about the same time.
If I then restart confd then everything works.

**Comment by bacongobbler** [comment] 2015-04-21 01:35
@mingfang interesting. If you can reproduce it using the [integration tests](https://github.com/kelseyhightower/confd/blob/master/.travis.yml#L18-L19) which test confd against v2.0.9, that would be appreciated.

**Comment by mingfang** [comment] 2015-04-21 04:10
The problem appears to only occur when both etcd and confd are started at the same time.
Unfortunately it looks like the existing integration tests starts etcd before running the tests.

**Comment by bacongobbler** [comment] 2015-04-21 04:13
in that case, it's probably due to etcd having some time to boot up before it starts accepting connections. Either that, or the go-etcd client does not have a [connection timeout](https://godoc.org/github.com/coreos/go-etcd/etcd#Client.SetDialTimeout) set up by default. Can you confirm that setting a DialTimeout on the etcd backend fixes this issue?

**Comment by mingfang** [comment] 2015-04-21 04:18
I would love to try.
How do I set the dial timeout?

**Comment by king6cong** [comment] 2016-05-05 03:49
Same problem here.
etcd & confd started at the same time, confd gives the error.
restart confd and the problem is gone.

version info:

# confd --version
confd 0.11.0

# etcd --version
etcd Version: 2.3.3
Git SHA: c41345d
Go Version: go1.6.2
Go OS/Arch: linux/amd64
