### ISSUE TITLE
[v0.12.0-alpha3] ls does not return empty list if there's nothing in it

### ISSUE THREAD

**Issue by ivankennethwang** [kelseyhightower/confd#430] opened 2016-04-08 04:36 UTC
etcd keys:

```
/staging/global/service/hosts/service-1
/staging/global/service/hosts/service-2
/staging/global/another-service/hosts
```

`{{ ls "/staging/global/service/hosts" }}`
returns `[service-1 service-2 staging]`

`{{ ls "/staging/global/another-service/hosts" }}`
returns `[staging]`

**Comment by davis12529** [comment] 2016-04-28 17:31
+1. `ls` returns first parent key if path is not found
   ```
 {{with := "/nginx/app/upstream"}}
    {{ if ls $upstream }}
    upstream {{$app}} {
        {{range ls $upstream}}
            {{with $server := printf "%s/%s" $upstream .}}
            {{with $proxy := getv $server}}
     ...
```
I get the error 
`<getv $server>: error calling getv: key does not exist: /nginx/app/upstream/nginx`

I realized that template_test.go does not have test cases for querying 
https://github.com/kelseyhightower/confd/blob/v0.12.0-alpha3/resource/template/template_test.go#L295-L306

**Comment by HeavyHorst** [comment] 2016-04-28 20:11
i can't reproduce this with the latest master:

etcdctl mkdir /staging/global/another-service/hosts

{{ ls "/staging/global/another-service/hosts" }}
returns []

i think this should be fixed with the next release.

**Comment by seanmcgary** [comment] 2016-05-05 06:36
I actually ran into some similar issues that seemed to be rooted in the [memkv](https://github.com/kelseyhightower/memkv) dependency. I opened a [PR](https://github.com/kelseyhightower/memkv/pull/11) that fixes the issues I was having which are the same as the ones mentioned by @ivankennethwang.

**Comment by jjjordanmsft** [comment] 2016-07-25 23:17
I've also run into this issue with Zookeeper.  It is indeed caused by an issue in memkv, and I've opened a PR (kelseyhightower/memkv#12) to fix it that seems to work better than the previous.

**Closed** 2017-08-23 08:18 UTC
Labels: bug
