### ISSUE TITLE
ERROR ParameterNotFound when using an ssm backend when parameter is only referenced in an "if exists" statement

### ISSUE THREAD

**Issue by lchisholmfp** [kelseyhightower/confd#652] opened 2018-01-05 00:30 UTC
This behaviour is different from using backend env. I would expect the mentioned error to happen if you called getv and it doesn't exist, but if the getv is wrapped in an if exists I don't think this behavior is desiarable.

**Comment by gdw2** [comment] 2018-01-31 01:20
@lchisholmfp , I'm not seeing this in 0.15.0 which was recently release.  Please try again...?

**Comment by okushchenko** [comment] 2018-02-20 14:09
@lchisholmfp closing the issue for now. Please, reopen if the issue is still present for you.

**Closed by okushchenko** 2018-02-20 14:09 UTC
Labels: bug
