### ISSUE TITLE
can I get values in my confd toml config file?

### ISSUE THREAD

**Issue by Mvpanswer7** [kelseyhightower/confd#543] opened 2017-03-07 07:39 UTC
can I get values stored in consul in my toml file to run different linux cmd? such like :

check_cmd = "/home/work/app/portal/myservice  configtest"
reload_cmd = "echo {{getv "/myservice/command"}}"

**Comment by HeavyHorst** [comment] 2017-03-07 10:54
Unfortunately not. You can only use {{.src}} in the check_cmd to reference the rendered source template.

**Comment by okushchenko** [comment] 2017-08-05 14:00
This behavior will not be supported. Closing as a duplicate of #79 #229 #344

**Closed by okushchenko** 2017-08-05 14:00 UTC
