### ISSUE TITLE
No ACL support for consul backend, although pull request is there (#369)

### ISSUE THREAD

**Issue by rares-aioanei** [kelseyhightower/confd#520] opened 2017-01-10 15:24 UTC
Sorry for the less-than-verbose comment, but since there is already a feature request (#146), everything that is to be said is already in there.

**Comment by bacongobbler** [comment] 2017-01-10 16:13
closing as a duplicate of another issue. Let's keep it all in one ticket.

**Closed** 2017-01-10 16:13 UTC
