### ISSUE TITLE
error calling getv: key does not exist:/XXX/XXX

### ISSUE THREAD

**Issue by aixushuai** [kelseyhightower/confd#607] opened 2017-09-27 06:53 UTC
env: confd-0.13.0  + etcdv3
Write multiple data to etcd at the same path, After the confd watch the event, the configuration is generated, his causes an error:key does not exist....
etcd data eg:
upstream/servers/app1/address 192.168.1.100
upstream/servers/app1/port 8080
upstream/servers/app1/weight 1
upstream/servers/app1/down false

I think this is the result of multiple events on etcd, causes no data to be obtained.
temporary solution: update backends/etcdv3/client.go. line:122
Add code: time.Sleep(time.Second * 2)

> 	for wresp := range rch {
			for _, ev := range wresp.Events {
				fmt.Println(string(ev.Kv.Key))
				// Only return if we have a key prefix we care about.
				// This is not an exact match on the key so there is a chance
				// we will still pickup on false positives. The net win here
				// is reducing the scope of keys that can trigger updates.
				for _, k := range keys {
					if strings.HasPrefix(string(ev.Kv.Key), k) {
						time.Sleep(time.Second * 2)
						return uint64(ev.Kv.Version), err
					}
				}
			}

**Comment by okushchenko** [comment] 2018-03-05 13:32
@aixushuai This issue is supposed to be fixed by #613. Please, reopen if the issue is still present.

**Closed by okushchenko** 2018-03-05 13:32 UTC
Labels: bug
