### ISSUE TITLE
Can write to environment variable?

### ISSUE THREAD

**Issue by yangjunsss** [kelseyhightower/confd#553] opened 2017-04-07 03:25 UTC
Hi, I have a requirement that need use environment variable as parameter input to start an application.On other way, we can rewrite the application to accept the config file to solve it but sometimes the application is not owned by us unfortunately. So I need find another way to set env to accomplish it. So does ``confd`` support writing to env variable? I can't find any infos in docs.Thanks.

**Comment by yangjunsss** [comment] 2017-04-08 15:11
I find out ``getenv`` which works for me,thx.

**Comment by regardfs** [comment] 2017-05-26 05:49
of course! Sure
If u read docs carefully, you will see **getenv** to retrive env parameters

**Comment by yangjunsss** [comment] 2017-05-26 06:21
Cool, so how to write the value to `env` directly in `toml` file?? For example:
```yml
[template]
src = "hosts.tmpl"
dest = "$env_name"
keys = [
  "/env",
]
```

Thanks

**Comment by okushchenko** [comment] 2017-05-26 10:39
@yangjunsss .toml configs are not templated by confd, so you can't embed environment variables in them. You can try to template them using `sed` command in your entrypoint script.

**Comment by okushchenko** [comment] 2017-08-05 14:19
@yangjunsss there is no way to set environment parameters using confd, it was intended to be used to template files.
I suggest the following workaround:
1. Run confd to template a file (e.g., `test.env`) in .env format, e.g.
```
KEY1=VALUE1
KEY2=VALUE2
```
2. Run `source test.env` before running your app to set environment variables from a file.

Closing the issue for now. Please, reopen if the workaround will not help.

**Closed by okushchenko** 2017-08-05 14:19 UTC
Labels: question
