### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by huwenzheng** [kelseyhightower/confd#551] opened 2017-04-05 11:12 UTC
基本描述：
       confd监控的key比较多，达到几千个。内存一直上涨不下降。cup下降后内存还是不下降。
![image](https://cloud.githubusercontent.com/assets/15844293/24702850/411a326e-1a33-11e7-98b7-32b757abef28.png)

**Comment by huwenzheng** [comment] 2017-04-05 11:14
the %MEM Can be up to 80% within two days

**Comment by huwenzheng** [comment] 2017-04-05 11:14
the backend is zookeeper

**Comment by HeavyHorst** [comment] 2017-04-05 16:17
could you set GODEBUG=gctrace=1 and wait for lines that start with scvg: to be printed, they will tell you the current memory usage.

How much watch events per second are there ?

**Comment by huwenzheng** [comment] 2017-04-06 01:47
I had monitor More than three thousand keys, 
![image](https://cloud.githubusercontent.com/assets/15844293/24734050/f26e1470-1aad-11e7-93a4-8fdfa4acaec8.png)
how to use GODEBUG=gctrace=1, I do not find debug information.

**Comment by huwenzheng** [comment] 2017-04-06 02:34
[root@qinhaiguan conf.d]# curl http://127.0.0.1:6060/debug/pprof/
<html>
<head>
<title>/debug/pprof/</title>
</head>
<body>
/debug/pprof/<br>
<br>
profiles:<br>
<table>

<tr><td align=right>0<td><a href="block?debug=1">block</a>

<tr><td align=right>7684<td><a href="goroutine?debug=1">goroutine</a>

<tr><td align=right>123<td><a href="heap?debug=1">heap</a>

<tr><td align=right>12<td><a href="threadcreate?debug=1">threadcreate</a>

</table>
<br>
<a href="goroutine?debug=2">full goroutine stack dump</a><br>
</body>
</html>

**Comment by HeavyHorst** [comment] 2017-04-07 16:31
The pprof profiles are unfortunately not visible. Could you attach the heap and the goroutine profiles ?

**Comment by okushchenko** [comment] 2017-08-05 14:11
Closing it as a duplicate of #550
@huwenzheng  please, attach the files in #550

**Closed by okushchenko** 2017-08-05 14:11 UTC
Labels: bug, duplicate

**Comment by rhubard** [comment] 2018-04-23 02:46
Hi,I also found the same problem, cpu inexplicably burst, how do I solve this problem?
