### ISSUE TITLE
pongo2 template format support?

### ISSUE THREAD

**Issue by wrouesnel** [kelseyhightower/confd#511] opened 2016-12-07 05:29 UTC
pongo2 is django-like templating engine in Go which compiles down to the regular golang template format.

The Jinja-like templates it's written in are somewhat more readable then Go's templating syntax in a lot of cases - it would be nice if confd could support this alternate format to make it easier to work with templates for people used to other languages.

**Comment by bacongobbler** [comment] 2016-12-07 06:10
dupe of #190

**Closed by bacongobbler** 2016-12-07 06:10 UTC
