### ISSUE TITLE
Better template engine?

### ISSUE THREAD

**Issue by hypergig** [kelseyhightower/confd#385] opened 2016-02-11 22:21 UTC
Coming from a jinja2 background, I find the golang text template engine... limited.

I was playing with the idea of bootstrapping a small python process that will build templates using jinja2 instead of golangs in confd. Then I can enjoy the full glory that is [jinja2.](http://jinja.pocoo.org/docs/dev/templates/)

I have a few thoughts on how to best do this without making it all too heavy but before investing the time  I was wondering if this makes sense?  Should I just invest in expanding golangs text templator to do more stuff?

I need some basic funcationallty like [reverse](http://jinja.pocoo.org/docs/dev/templates/#reverse), [sort](http://jinja.pocoo.org/docs/dev/templates/#sort), and [for loop speical vars](http://jinja.pocoo.org/docs/dev/templates/#for).

Thoughts?

**Comment by bacongobbler** [comment] 2016-02-11 22:36
Closing as a duplicate of #190. We're not planning on changing the templating engine any time soon.

To address your functionality questions, [text/template](https://golang.org/pkg/text/template/) has for loops:

> {{range pipeline}} T1 {{end}}

As for sort, the keys are already in sorted order:

> If the value is a map and the keys are of basic type with a defined order ("comparable"), the elements will be visited in sorted key order.


Would you mind opening a separate issue for implementing a reverse function? Thanks!

**Closed by bacongobbler** 2016-02-11 22:36 UTC

**Comment by hypergig** [comment] 2016-02-11 22:53
@bacongobbler sure, forward sorted order.. but say you want to sort reverse alphabetized? Say you're building a giant list of urls for some haproxy config file and you want longer urls of the same prefix to be written first.. e.g.
```
/store/checkout
/store
```
Using range as it is, I would get
```
/sore
/store/checkout
```
No good when using starts with in haproxy.  Also, with range you are forced to sort based on key... you have to do some jankery if your keys are, for example, urls with query strings and special characters and whatnot.  Just a bit tricky. I just wish I could do something like `block-o-data | map(attribute='urls') | reverse`.
