### ISSUE TITLE
rethinkdb backend

### ISSUE THREAD

**Issue by vikstrous** [kelseyhightower/confd#483] opened 2016-09-14 21:40 UTC
I'm considering using confd with rethinkdb and I might try to implement a rethinkdb backend. Has anyone done this already? If I do this, would it be accepted upstream?

**Comment by bacongobbler** [comment] 2016-09-14 22:13
closing as a duplicate of #414

**Comment by bacongobbler** [comment] 2016-09-14 22:13
oops sorry meant a different issue :)

**Comment by bacongobbler** [comment] 2016-09-14 22:15
yes this would be an accepted feature, however kelsey has been away from the helm for some time (see #460).

**Closed** 2018-03-24 15:32 UTC
Labels: enhancement
