### ISSUE TITLE
getv results in different values using consul vs. etcd backend 

### ISSUE THREAD

**Issue by cgswong** [kelseyhightower/confd#215] opened 2015-03-03 20:25 UTC
Template file snippet:
```
cluster   => {{getv "/services/logging/es/cluster"}}
```
Using etcd backend the template file correctly gets populated:
```
cluster   => "es01"
```
Using consul backend the template file ends up with:
```
cluster   => value="es01"
```
Checking consul (curl -L http://172.17.8.101:8500/v1/kv/services/logging/es/cluster?raw) the raw value is:
```
value="es01"
```
Is this expected behavior? If so, what should be the correct entry in the template?

**Comment by bacongobbler** [comment] 2015-03-03 20:43
The correct value should be the former for consul. I suspect that there may have been an internal client change if this worked in previous versions of confd.

**Comment by cgswong** [comment] 2015-03-05 19:45
Both 0.6.3 and 0.7.1 result in the same behaviour. However, the KV method actually makes a difference. For example:
```
curl -L http://${COREOS_PRIVATE_IPV4}:8500/v1/kv/services/logging/es/cluster -XPUT -d value="es01"
```
The above results in:
```
cluster => value="es01"
```
Removing the `value=` clause from the curl statement results in the correct value being used:
```
curl -L http://${COREOS_PRIVATE_IPV4}:8500/v1/kv/services/logging/es/cluster -XPUT -d "es01"
```
The above results in:
```
cluster => es01
```
When using etcd, the latter results in a blank value, i.e. `cluster => ' while the former works as expected.

**Comment by bacongobbler** [comment] 2015-03-24 06:34
Where's the original documentation coming from? `-d value="es01"` will set that as the literal key... So it's working as intended.

**Comment by cgswong** [comment] 2015-03-24 15:53
The etcd documents use `-d value="<value>"` or `-d value=<value>` and this does load the data correctly. See https://github.com/coreos/etcd/blob/master/Documentation/api.md

Maybe this is an etcd issue instead since it is more typical to use `-d <value>`?

**Comment by bacongobbler** [comment] 2015-03-24 15:58
Yes, this seems more like a doc issue on their end. Everything here looks fine on confd's end.

I'm going to go ahead and close this. Please feel free to post another bug if you see something in the documentation that is incorrect. We'll take a look and update it accordingly. Thanks!

**Closed by bacongobbler** 2015-03-24 15:58 UTC

**Comment by cgswong** [comment] 2015-03-25 00:57
@bacongobbler It's not an Etcd documentation issue, it's an Etcd API issue (or more accurately both). I've tested with a few Etcd versions (0.4.6/7, 2.0.5) and not putting `-d value=<value>` results in an empty value. But yes, this seems like something to log with the Etcd guys.
