### ISSUE TITLE
Question: Generating JSON while using .Key and .Value

### ISSUE THREAD

**Issue by logikal** [kelseyhightower/confd#214] opened 2015-03-01 09:52 UTC
I have the following template to generate json configs for sensu. The problem is that accursed trailing comma in json.

Most examples I see use `join`, but I haven't found a way to use that while also using `.Key` and `.Value`.

Storing everything for $datacenter in json is possible, but unwanted. It'd work for this, but not some other files I need to generate.

Template:

``` gotemplate
{
  {{range $datacenter := lsdir "/sensu/relay"}}
  "{{base $datacenter}}": {
      {{$config := printf "/sensu/relay/%s/*" $datacenter}}{{range gets $config}}
      "{{base .Key}}": "{{.Value}}",
      {{end}}
  },
    {{end}}
}
```

Output:
``` json
{
  "ams1": {
      "host": "graphite-mdw1.foo.net",
      "index": "0",
      "location": "production_ams1",
      "port": "2003",
  },
  "dfw1": {
      "host": "graphite-mdw1.foo.net",
      "index": "0",
      "location": "production_dfw1",
      "port": "2003",
  },
  "iad1": {
      "host": "graphite-mdw1.foo.net",
      "index": "0",
      "location": "production_iad1",
      "port": "2003",
  },
  "mdw1": {
      "host": "graphite-mdw1.foo.net",
      "index": "0",
      "location": "production_mdw1",
      "port": "2003",
  },
  "mdw3": {
      "host": "graphite-mdw1.foo.net",
      "index": "0",
      "location": "production_mdw3",
      "port": "2003",
  },
  "sjc1": {
      "host": "graphite.sjc1.foo.net",
      "index": "1",
      "location": "production_sjc1",
      "port": "2003",
  },
}

**Comment by bacongobbler** [comment] 2015-03-20 22:25
closing as a duplicate of #209

**Closed by bacongobbler** 2015-03-20 22:25 UTC
Labels: resource/template
